### PR TITLE
Config V2 (yes)

### LINKED ISSUE #15: Setting non-number values in the config file for scroll speed and width breaks (a lot)
setting the width or scroll_speed to a non-numerical value prevents the input display from loading entirely, it is just uncolored, and static. In some instances, doing this specifically to the scroll_speed results in all input bars being crammed into the top left corner.
Restarting the program can fix this, but sometimes just breaks the config further by more and more sections missing, requiring deletion of the config entirely.

### PR DESCRIPTION
**Pull request by SkyJumper409x**
So this is a lot of stuff
Config v2 started as mostly a naming changes thing, and like fixing a bug. Apparently I felt like spending more time on this so I made a **full Configuration UI**. This aims to obsolete manually editing the config. This sorta fixes #15 because the config shouldn't be directly edited anymore anyway.

**This needs a lot of testing** because of the amount of *stuff* it has.
I tried chopping it up into smaller pieces, but as it basically restructures everything config related, that was just not happening.

The significant additions:
- `ConfigInterface.tscn`
The scene containing the Config UI. it is in the folder `./ConfigInterface/`, along with everything else that the ConfigInterface uses.
- `Binding.gd`
I found binding handling in the InputBtn.gd really hard to work with, so I decided to make a script whichs purpose is to ease rebinding buttons.
- `Config.gd`
Almost everything read from the config was stored in `Singleton.gd`. This script is now used for that.
- The script that I spent the most time on by a landslide: `ConfigHandler.gd`
All config loading and saving has been moved here. This is a Global/Singleton script that loads the Config upon `_ready()`ing up, and saves the config upon program exit. `InputBtn`s call `ConfigHandler.load_binding(self)`, instead of loading everything manually from the config. It has full support for loading all previous Config Versions, and also has (barely tested) code to save configs for older versions.

A lot has been moved out of `Singleton.gd`, but it is still used for various things that require a Global variable. It also calls `ConfigHandler.save_config(2)` before exiting.
Oh, about that. 
The program will no longer automatically quit when the User attempts to close the window. This is mostly to ensure the config can be saved properly.

I attached the file [cfg_v2_syntax.txt](<https://github.com/user-attachments/files/15930833/cfg_v2_syntax.txt>) to this PR, i used it for keeping track of the config differences. It might not be up to date with the code entirely, but it should give a rough idea of the new structure.

Yea this somehow turned into 9 commits idk its probably more like 5 but that isn't much better is it.
This literally was way too complicated I had the Godot docs open all the time while coding but it is done now.

### CODE REVIEW

**Comment by raphaelgoulart** [comment]
I'll be testing this over the weekend, and hopefully enlisting others to test as well! Thank you very much for your hard work!

**Comment by SkyJumper409x** [comment]
okay! I made a mac build for a friend of mine before, she will test the mac config v2 build too when she has the time.

**Comment by SkyJumper409x** [comment]
> Thank you very much for your hard work!

I wanted to fix bugs that annoyed me and decided it would be easier to just start from 0. It really is as shrimple as that :3

**Comment by raphaelgoulart** [comment]
Found one minor issue in my brief testing:
- Hamburger button is not clickable once you hide it. Probably not a huge issue since you can just hit Esc to reopen it (please add this info to README.md, or let me know if you want me to do it myself)
- "Always show hamburger button" option isn't taken into account when loading the program - I disabled it (so it should be hidden), restarted it and it still appears. Option itself seems to be saved though, as the toggle remains how I left it before closing.

Otherwise, looking/feeling pretty good so far!

**Comment by raphaelgoulart** [comment]
No problem, in fact I intend on creating a new release once this is approved, I've had a few people test this and it worked fine apart from what I mentioned

**Comment by SkyJumper409x** [comment]
The recently pushed commits should address the issues you mentioned.
If a Control is hidden with the `hide()` function, the `mouse_entered` and `mouse_exited` signals are no longer emitted.
I now use the `modulate.a` property (which is the alpha channel of the modulate Color` to hide/show the button. As it is a float value ranging from 0 to 1, instead of a `bool`, I was able to add fade in/out to the hiding/showing of the button.
Also, the hamburger button will show regardless of `always_show_hamburger` if the user hovers over it.
I apparently forgot to add code that hides the button in the `_read()` function if `always_show_hamburger` is `false`, woops.
That code was added now.

**Comment by SkyJumper409x** [comment]
> No problem, in fact I intend on creating a new release once this is approved, I've had a few people test this and it worked fine apart from what I mentioned

In that case, I will update the Readme to fit the new stuff. Should I do so in a seperate PR once the new version is released, or add it to this PR?

**Comment by raphaelgoulart** [comment]
> In that case, I will update the Readme to fit the new stuff. Should I do so in a seperate PR once the new version is released, or add it to this PR?

Add it to this one, please

**Comment by SkyJumper409x** [comment]
object leak on exit is simple, `ConfigHandler.current_config` needed to be `free()`'d manually upon program exit.

**Comment by SkyJumper409x** [comment]
As for the readme,
I moved the FAQ-like section up as solutions for common issues should be easy to find.
The "Controls" and "Settings" sections were updated. "Settings" has a subsection with the info for release 0.0.4 and prior.

**Comment by raphaelgoulart** [comment]
Ok; let me know once you feel this is 100% and I'll do another round of testing, then merge

**Comment by SkyJumper409x** [comment]
i feel it is 100% now
i was ADHD'ing the readme, thats why its like 3 commits :sweat_smile: 
u can merge now unless theres an issue

**Pull request merged**
